_base_: default.yml
model:
  clip_model_name: ViT-B/16
  keep_cls: false
  keep_end_seq: false
  model_name: dinov2_vitb14_reg
  proj_class: vitb_mlp_infonce
  proj_model: ProjectionLayer
  proj_name: vitb_mlp_infonce
  resize_dim: 518
  type: DINOText
  use_avg_text_token: false
  with_bg_clean: true
