defaults:
  - _self_
  - task: hra_instruction

name: train_diffusion_lbm_instruction_hra
_target_: diffusion_policy.workspace.train_diffusion_lbm_hra_image_workspace.TrainDiffusionLargeBehaviourModelHRAImageWorkspace

task_name: ${task.name}
shape_meta: ${task.shape_meta}
exp_name: "default"
use_embodiment_normalizer: False
use_ts_normalizer: True

n_action_steps: 8

policy:
  _target_: diffusion_policy.policy.diffusion_lbm_hra_timm_policy.DiffusionLargeBehaviourModelHRATimmPolicy

  shape_meta: ${shape_meta}
  
  noise_scheduler:
    _target_: diffusers.DDIMScheduler
    num_train_timesteps: 50
    beta_start: 0.0001
    beta_end: 0.02
    # beta_schedule is important
    # this is the best we found
    beta_schedule: squaredcos_cap_v2
    clip_sample: True
    set_alpha_to_one: True
    steps_offset: 0
    prediction_type: epsilon # or sample

  obs_encoder:
    _target_: diffusion_policy.model.vision.timm_obs_encoder.TimmObsEncoder
    shape_meta: ${shape_meta}

    model_name: 'vit_base_patch16_clip_224.openai'
    use_low_dim_encoder: False
    pretrained: True
    frozen: False
    use_lora: False
    lora_rank: 8
    drop_path_rate: 0.0
    global_pool: ''
    feature_aggregation: 'cls_token'
    position_encording: 'sinusoidal' # 'learnable' or 'sinusoidal'. it only works for transformer

    # it only works for resnet. 32 (7x7) or 16 (14x14)
    downsample_ratio: 32

    transforms:
      - type: RandomCrop
        ratio: 0.95
      - _target_: torchvision.transforms.ColorJitter
        brightness: 0.3
        contrast: 0.4
        saturation: 0.5
        hue: 0.08

    use_group_norm: True
    share_rgb_model: False
    imagenet_norm: True
    three_augment: False
    fused_model_name: ''
    fused_model_frozen: False
    text_encoder_name: ''
    text_encoder_frozen: False
    text_encoder_feature_dim: 128

  num_inference_steps: 16
  input_pertub: 0.1 # reference: https://github.com/forever208/DDPM-IP
  # train multiple diffusion steps per obs encoder forward pass
  # doing this too much will cause instability!
  diffusion_step_embed_dim: 128  # the dimension for diffusion timestamp features
  n_layer: 8
  n_head: 12
  n_emb: 768
  # n_layer: 12
  # n_head: 16
  # n_emb: 2048

  use_embodiment_normalizer: ${use_embodiment_normalizer}
  use_ts_normalizer: ${use_ts_normalizer}
  use_adaptive_layernorm: True
  use_adaptive_layerscale: True

ema:
  _target_: diffusion_policy.model.diffusion.ema_model.EMAModel
  update_after_step: 0
  inv_gamma: 1.0
  power: 0.75
  min_value: 0.0
  max_value: 0.9999

dataloader:
  batch_size: 64
  num_workers: 8
  shuffle: True
  pin_memory: True
  persistent_workers: True

val_dataloader:
  batch_size: 64
  num_workers: 8
  shuffle: False
  pin_memory: True
  persistent_workers: True

optimizer:
  _target_: torch.optim.AdamW
  lr: 3.0e-4
  betas: [0.95, 0.999]
  eps: 1.0e-8
  weight_decay: 1.0e-6
  encoder_weight_decay: 1.0e-6

training:
  ckpt_path: ""
  device: "cuda:0"
  seed: 42
  debug: False
  resume: False
  # optimization
  lr_scheduler: cosine
  lr_warmup_steps: 1000
  num_epochs: 120
  gradient_accumulate_every: 1
  layer_decay: 1.0
  # EMA destroys performance when used with BatchNorm
  # replace BatchNorm with GroupNorm.
  use_ema: True
  freeze_encoder: False
  # training loop control
  # in epochs
  checkpoint_every: 100
  val_every: 5
  sample_every: 5
  # steps per epoch
  max_train_steps: null
  max_val_steps: null
  # misc
  tqdm_interval_sec: 1.0
  encoder_lr_coefficient: 0.1

logging:
  project: hra
  resume: False
  mode: online
  name: ${now:%Y.%m.%d-%H.%M.%S}_${name}_${task_name}
  tags: ["${name}", "${task_name}", "${exp_name}"]
  id: null
  group: null

checkpoint:
  topk:
    monitor_key: train_loss
    mode: min
    k: 5
    format_str: 'epoch={epoch:04d}-train_loss={train_loss:.3f}.ckpt'
  save_last_ckpt: False
  save_last_snapshot: False
  only_save_recent: True

multi_run:
  run_dir: data/outputs/${now:%Y.%m.%d}/${now:%H.%M.%S}_${name}_${task_name}
  wandb_name_base: ${now:%Y.%m.%d-%H.%M.%S}_${name}_${task_name}

hydra:
  job:
    override_dirname: ${name}
  run:
    dir: data/outputs/${now:%Y.%m.%d}/${now:%H.%M.%S}_${name}_${task_name}
  sweep:
    dir: data/outputs/${now:%Y.%m.%d}/${now:%H.%M.%S}_${name}_${task_name}
    subdir: ${hydra.job.num}
